on: [push]

jobs:
  push:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [latest]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: qwerty12345
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM update
        run: npm install --global npm@latest

      - name: NPM install
        run: npm install

      - name: Check prettier
        run: npm run prettier:write

      - name: Check eslint
        run: npm run lint

      - name: Check tests
        run: npm run tests

      - name: Check development build
        run: npm run development

      - name: Check production application build
        run: npm run production:default
